# -*- coding: utf-8 -*-
"""SistemaBancario.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gAM21Xi0tzz8-VXhzlhXClwA6dJTBcCp
"""

LIMITE_SAQUE = 500
LIMITE_SAQUES_DIARIO = 3
saldo = 0

from datetime import datetime
depositos = []
saques = []

def depositar(valor):
    global saldo

    if valor > 0:
        registro = []
        registro.append(valor)
        registro.append(datetime.now())
        registro.append("deposito")
        depositos.append(registro)
        saldo += valor

        print(f"Depósito realizado com sucesso!")
        return True
    else:
        print(f"Valor inválido!")
        return False

def sacar(valor):
    global saldo

    quant_saques = contar_saques_hoje()
    if quant_saques >= LIMITE_SAQUES_DIARIO:
        print("Você atingiu o limite de saques diário!")
        return False

    if valor <= 0:
        print("Valor inválido!")
        return False

    if saldo - valor < 0:
        print("Saldo insuficiente!")
        return False

    if valor > LIMITE_SAQUE:
        print(f"Valor do saque ultrapassa o limite permitido de R$ {LIMITE_SAQUE}!")
        return False

    registro = []
    registro.append(valor)
    registro.append(datetime.now())
    registro.append("saque")
    saques.append(registro)
    saldo -= valor

    print(f"Saque realizado com sucesso!")
    return True

def contar_saques_hoje():
    hoje = datetime.now().date()
    contador = 0
    for saque in saques:
        if saque[1].date() == hoje:
            contador += 1
    return contador

def imprimir_extrato():
    extrato = depositos + saques
    extrato.sort(key=lambda x: x[1])

    print("""
    --------------------------------
    ------- EXTRATO BANCÁRIO -------
    --------------------------------
    """)

    for registro in extrato:
        tipo = registro[2]
        valor = registro[0]
        data = registro[1].strftime('%d/%m/%Y')
        if tipo == "deposito":
            print(f"     Depósito: R$ {valor:.2f} em {data}")
        elif tipo == "saque":
            print(f"     Saque:    R$ {valor:.2f} em {data}")

    print(f"    --------------------------------")
    print(f"    ------   SALDO: R$ {saldo:.2f}")
    print(f"    --------------------------------")

while True:
    opcao = input("""
       Digite a opção desejada:
       d => para depositar
       s => para sacar
       e => para imprimir extrato
    """)

    if opcao.lower() == "d":
        valor = input("Digite o valor a ser depositado: ")
        if valor.isnumeric():
            valor = float(valor)
            depositar(valor)
        else:
            print("Valor inválido!")
            continue
    elif opcao.lower() == "s":
        valor = input("Digite o valor a ser sacado: ")
        if valor.isnumeric():
            valor = float(valor)
            sacar(valor)
        else:
            print("Valor inválido!")
            continue
    elif opcao.lower() == "e":
        imprimir_extrato()
    else:
        print(f"OPCAO DIGITADA: {opcao}")
        print("Opção inválida! Digite uma das opções.")